#version 460

#extension GL_EXT_descriptor_heap : enable
#extension GL_EXT_nonuniform_qualifier : enable

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

layout(descriptor_heap, rgba16f) uniform image2D Textures[];

layout(push_constant) uniform PushConstants {
    int image_index;
} pc;

#define IMAGE Textures[pc.image_index]

void main() {    
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(IMAGE);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

        if(gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0)
        {
            color.x = float(texelCoord.x)/(size.x);
            color.y = float(texelCoord.y)/(size.y);	
        }
    
        imageStore(IMAGE, texelCoord, color);
    }
}
